canonical/docs.ubuntu.com

.gitignore
Adding:
- `.envrc` for direnv
- `.python-version` for pyenv
=> Add some local environment files to gitignore

package.json, static/sass/homepage.scss, templates/includes/layout.html, templates/index.html
QA
---
``` bash
./run
```
Go to <http://127.0.0.1:8007>. See that it looks unterrible.
=> Homepage styling

static/sass/homepage.scss, templates/index.html
- Add links to "project" names
- Make sure external link icons look okay
- Change documentation link text and targets
=> Tweak homepage content

redirects.yaml
Page removed for duplication of content
=> Redirect build-device/assertions to reference/assertions

templates/error/404.html
QA
==
Run the site (`./run`), go to <https://docs.ubuntu.com/maas/2.1/en/a-fake-page>.
=> Hack together a 404 page for the docs site, to send people somewhere useful

redirects.yaml
QA
--
``` bash
./run
```
Go to <http://127.0.0.1:8007/maas/devel/>, check it redirects to <http://127.0.0.1:8007/maas/devel/en/>.
=> Redirect /maas/devel/

rebuild-docs
- Adding build steps to install git-repo in the path and sync from the ubuntu-core-docs dir
- Works On My Machine (:tm:)
Open to suggestions on where/how to put this code.
=> Tentative build steps for ubuntu-core-docs

.travis.yml, webapp/tests/test_redirects.py
Set up unit testing for redirects config, to avoid potential issues.
This PR will include changes for PR webhooks.
To run the tests, use this command: `python manage.py test`
=> Redirects testing

rebuild-docs
They are huge, and filling up our servers, but we're not even using them yet.
=> Stop building phone docs

.gitignore, rebuild-docs, redirects.yaml, templates/index.html
Build landscape docs, link to them fromm the homepage, setup redirect
for the front page.
QA
--
``` bash
./rebuild-docs # Build docs including landscape
./run          # Run server
```
Go to <http://127.0.0.1:8007> and browse to landscape docs in all their
glory.
=> Add landscape docs

README.md
QA
--
Try out the new [readme instructions](https://github.com/nottrobin/docs.ubuntu.com/tree/43-repo-install-instructions).
=> repo install instructions

templates/includes/layout.html
QA
--
`./run`
Go to <http://127.0.0.1:8007/> - see the hearty icon in the browser tab.
=> Add hearty favicon to index page

rebuild-docs, templates/index.html
QA
--
``` bash
./rebuild-docs
./run
```
Go to <http://127.0.0.1:8007>, see the link to phone docs, click it, click around, check things work. If they don't, blame @pmahnke ;)
=> Add phone documentation

build-docs.sh
``` bash
rm -rf build/conjure-up
./run
```
Check http://0.0.0.0:8007/conjure-up/2.2.0/en/
=> conjure-up should have versions

templates/index.html
[List of work items including drive-bys]
=> MAAS: Update index.html to point to 2.3 of the docs

redirects.yaml
[List of work items including drive-bys]
=> Updated conjure-up.io/docs redirect to 2.4.0

build-docs.sh, templates/index.html
changed build-docs and index to add Styleguide repo
Check the style guide docs are built
Check the link from the main index page to the Style Guide docs works
=> Add Style Guide

package.json, static/sass/homepage.scss, templates/includes/layout.html, templates/index.html, yarn.lock
- Updated site to Vanilla 1.6.6
- `./run`
- Navigate to http://0.0.0.0:8007/
- Check that everything looks good
Fixes #140
=> Update to Vanilla 1.6.6

build-docs.sh, redirects.yaml, templates/index.html
- Added docs for Snap Enterprise Proxy
- Smoke tested local availability from `./run`
- N/A
- N/A
=> Add Snap Enterprise Proxy docs

requirements.txt, webapp/urls.py
Fixes #149
QA
--
First **CONNECT TO THE VPN**. Then:
``` bash
./run
```
Go to http://0.0.0.0:8007/search?q=cloud&domain=docs.jujucharms.com, see "returned 398 results" (or similar).
=> Fix total search results

templates/index.html
* Added snap-store-proxy logo
* Verified logo looks as expected locally
=> Add snap store proxy logo

renovate.json
This config will group all minor or point updates into one PR. Much cleaner.
From docs.snapcraft.io.
=> Use our standard renovate.json

templates/index.html
Update the links to match the new URLs
- Check that the new links work
- Check the addition of dqlite looks ok
Fixes https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/228
=> Update the links to docs

renovate.json
Renovate to ignore future updates of gitdb2
=> Renovate ignore gitdb2

Dockerfile
QA
--
```
DOCKER_BUILDKIT=1 docker build -t docs .
docker run -ti -p 8666:80 --env SECRET_KEY=dafgdfg docs
```
Go to http://localhost:8666, see it work.
=> Add setuptools to make gevent happy

.gitignore, Dockerfile, package.json, static/js/cookie-policy.js, static/js/global-nav.js, static/sass/main.scss, templates/footer.html, templates/includes/layout.html, webpack.config.entry.js, webpack.config.js, webpack.config.rules.js, yarn.lock
- Add global-nav and cookie-policy dependencies
- Built with webpack
- Load the site
- Check the global nav works as expecred
- Check the cookie policy is there and works
- Go to the footer and manage your cookies and see it opens again
Fixes https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/268
=> Integrate cookie-policy v3.0.4

package.json
Replace libsass with Dart Scss
Check the site loads and looks ok
=> Replace libsass with Dart Scss

static/sass/main.scss, templates/index.html
- Updated landing page as per [doc](https://docs.google.com/document/d/1mcfPYByoIT_iFOot6fxqq_bXX9p9vENWkLt4-ZI22Qg/edit)
- Visit demo https://docs-ubuntu-com-358.demos.haus/
- See that requested changes were made 
https://warthogs.atlassian.net/browse/WD-4994
=> Add matrix item and update copy

konf/site.yaml
K8s config - Use PS5 docker registry
Fixes #360
=> K8s config - Use PS5 docker registry

templates/index.html
- Updates the home page based on [copydoc](https://docs.google.com/document/d/1wc8f4Vh8q5-EaYCGNHCjNJmRrY21fFx8YyNZV8DmPUs/edit)
- Go to https://docs-ubuntu-com-366.demos.haus/
- Check that the changes match the [copydoc](https://docs.google.com/document/d/1wc8f4Vh8q5-EaYCGNHCjNJmRrY21fFx8YyNZV8DmPUs/edit)
Fixes https://warthogs.atlassian.net/browse/WD-12669
=> chore: Add 'Charmed Kubeflow', 'Charmed MLflow' and 'Data Science Stack' to the products list

templates/index.html
Update Juju docs Link
[List of work items including drive-bys]
=> Update index.html Juju docs

templates/index.html
Modify the Styling on the table to make sure in smaller screen it doesn't  show too small, maintaining the size of at least 800px, and is scrollable horizontally
Check the demo link, view in smaller screen and test table shows correctly and is scrollable
=> Fix table scroll

templates/index.html, yarn.lock
Update the list to show Ubuntu for developers 
test the branch by running ./run and make sure the url and text is correct
=> Update: update list to show ubuntu for developers

templates/index.html
Solve issues submitted by form:
- [Containers column should be Containers and VMs](https://warthogs.atlassian.net/browse/DOCPR-1569)
- [MicroCloud URL](https://warthogs.atlassian.net/browse/DOCPR-1571)
- [Delete the 'Ubuntu on AWS' entry](https://warthogs.atlassian.net/browse/DOCPR-1572)
1. Pull review 
2. run using the command `./run`
3. Make sure that the comments in each issues is solve
[DOCPR-1569](https://warthogs.atlassian.net/browse/DOCPR-1569)
[DOCPR-1571](https://warthogs.atlassian.net/browse/DOCPR-1571)
[DOCPR-1572](https://warthogs.atlassian.net/browse/DOCPR-1572)
[DOCPR-1569]: https://warthogs.atlassian.net/browse/DOCPR-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCPR-1571]: …
=> fix: solve DOCPR- 1569, 1571, 1572

templates/index.html
Update the kubernetes links in both the table and list 
[Jira Card](https://warthogs.atlassian.net/browse/DOCPR-1762)
=> feat: update the Kubernetes links in both table and list

templates/index.html
Updated Snap Store Proxy name and link to correct Enterprise Store
=> Update Snap Store Proxy name
