redirects.yaml, requirements.txt
- Make it language agnostic - all redirects should work for any language folder
- Remove trailing slashes, html extensions and "index" pages
Run the site and check the following redirects happen:
- `/core` -> `/core/en/`
- `/core/en` -> `/core/en/`
- `/core/en/index` -> `/core/en/`
- `/core/en/guides/build-device/image-building/` -> `/core/en/guides/build-device/image-building`
- `/core/en/guides/build-device/image-building.html` -> `/core/en/guides/build-device/image-building`
=> Improve redirects

rebuild-docs, templates/includes/layout.html
to both index.html and the built docs pages
fixes #10.
QA
---
``` bash
snap refresh documentation-builder --channel candidate
./rebuild-docs
./run
```
Check the homepage and all the built docs have tag manager snippet code.
=> Add tag manager code

redirects.yaml
QA
--
```
./run
```
<http://127.0.0.1:8007/maas/2.1/> -> check it goes to <http://127.0.0.1:8007/maas/2.1/en/>.
=> Make sure /maas/2.1/ redirects to /maas/2.1/en/

redirects.yaml
Stop /core/en/ redirect looping.
Make sure /maas/ links correctly point to versioned URL
Make sure to remove trailing /index and .html as required.
These redirects should all work:
- `/core`
- `/core/`
- `/core/en`
Should go to ➡️ `/core/en/`
- `/core/en/test/`
- `/core/en/test/index`
- `/core/en/test.html`
Should go to ➡️ `/core/en/test`
- `/maas`
- `/maas/`
- `/maas/2.1`
- `/maas/2.1/`
- `/maas/2.1/en`
- `/maas/en`
- `/maas/en/`
Should go to ➡️ `/maas/2.1/en/`
- `/maas/2.1/en/test/`
- `/maas/2.1/en/test/index`
- `/maas/2.1/en/test.html`
Should go to ➡️ `/maas/2.1/en/test`
=> Remove redirect loop and update redirects

rebuild-docs, redirects.yaml
QA
--
``` bash
./rebuild-docs
./run
```
Go to <http://127.0.0.1:8007/core/en/reference/interfaces/index> and click around the documentation bit, check all links still work.
=> Allow /index at end of paths

requirements.txt, templates/search.html, webapp/settings.py, webapp/urls.py
Get search working at `/search`.
At present this is completely unstyled. The style will come later.
QA
---
*Connect to the VPN* and run the site natively:
``` bash
virtualenv env
env/bin/pip install -r requirements.txt
env/bin/python manage.py runserver 0.0.0.0:8007
```
Now visit <http://127.0.0.1:8007/search>. Check it functions properly (although it will look horrible).
=> Implement search view with ubuntudesign.gsa

templates/maas/1.9/en/cluster-configuration.html, templates/maas/1.9/en/configure.html, templates/maas/1.9/en/hardware-enablement-kernels.html, templates/maas/1.9/en/install.html, templates/maas/1.9/en/kernel-options.html, templates/maas/1.9/en/maascli.html, templates/maas/1.9/en/networks.html, templates/maas/1.9/en/nodes.html, templates/maas/1.9/en/orientation.html, templates/maas/1.9/en/physical-zones.html
See how <https://docs.ubuntu.com/maas/1.9/en/maascli> has missing images? This fixes it.
QA
--
``` bash
./run
```
Visit <http://127.0.0.1:8007/maas/1.9/en/maascli>, see that images work.
=> Fix images in 1.9 documentation

package.json, rebuild-docs, requirements.txt, templates/includes/layout.html, templates/index.html, templates/search.html
Make the search form look relatively nice, a bit like the designs.
Also, add search to header of all documentation pages, using [new feature](https://github.com/CanonicalLtd/documentation-builder/pull/56) in documentation-builder.
Also, the header should look different if you provide different `domain` options.
QA
==
Make sure you're connected to the VPN.
``` bash
snap refresh documentation-builder --channel candidate  # Install documentation-builder v1.3.0
./rebuild-docs
virtualenv env
env/bin/pip install requirements.txt
env/bin/python ./manage.py runserver 0.0.0.0:8007
```
- Go to <http://127.0.0.1/search>. Try it out. See that it is good.
- See that <http://127.0.0.1/search?domain=docs.ubuntu.com/maas> is subtly different
- and that …
=> Search form styling

redirects.yaml
Add redirects per #49 
Run server and check the links redirect to the correct location.
This can be done with curl, ie:
```
curl --silent -I http://127.0.0.1:8007/maas/2.1/en/installconfig-deploy-nodes | grep Location
```
=> Add redirects for maas 2.1 installconfig pages

.gitignore, rebuild-docs, redirects.yaml, templates/index.html
Fixes #47
QA
--
``` bash
./run
```
Go to <http://127.0.0.1:8007/>, click "Read the documentation-builder documentation". Check it works and looks okay.
If you have issues with the Builder documentation itself, please file them as [issues against documentation-builder](https://github.com/canonicalltd/documentation-builder/issues/new).
=> Add docs for documentation-builder

.gitignore, rebuild-docs, templates/index.html
Add Conjure-up docs from https://github.com/CanonicalLtd/docs-conjure-up/
- ./rebuild-docs
- ./run
- Go to http://localhost:8007/ and check the Conjure-up section and click through
- You should end up at http://localhost:8007/conjure-up/en
- Click around a bit, make sure things look pretty
=> Add Conjure-up docs

redirects.yaml
search is currently broken, 'cos it redirects: https://docs.ubuntu.com/search
This should fix it.
QA
--
**Connect to Canonical VPN**
``` bash
./rebuild-docs
./run
```
Go to <http://127.0.0.1:8007/maas>, use the search box, top left, check it works
=> Don't 301 /search

redirects.yaml
QA
--
Run the site (`./run`). Go to <http://127.0.0.1:8007>. Follow link to
landscape docs. See that it is at <http://127.0.0.1:8007/landscape/en/>
instead of a sub-page.
=> No longer need special redirect for landscape

redirects.yaml
Fixes #76
```
/maas/2.2/en/installconfig-nodes-hw-testing > /maas/2.2/en/nodes-hw-testing
/maas/2.1/en/installconfig-add-nodes > /maas/2.1/en/nodes-add
/maas/2.2/en/installconfig-add-nodes > /maas/2.2/en/nodes-add
/maas/2.1/en/installconfig-commisson-nodes > /maas/2.1/en/nodes-commission
/maas/2.2/en/installconfig-commisson-nodes > /maas/2.2/en/nodes-commission
/maas/2.2/en/installconfig-nodes-deploy > /maas/2.2/en/nodes-deploy
/maas/2.2/en/installconfig-nodes-power-types > /maas/2.2/en/nodes-power-types
/maas/devel/en/intel-rsd > /maas/devel/en/nodes-comp-hw
/maas/2.2/en/intel-rsd > /maas/2.2/en/nodes-comp-hw
```
``` bash
./run
```
Check the aforementioned redirects work as expected.
=> MAAS hardware testing redirects

redirects.yaml, run, templates/index.html
- add versions option to 'run'
- add redirects for versions
- fix link on index page to point to current version
build, see that the conjure up link goes to conjure up docs, check that the versions are listed in the navigation and that they work
=> Add versions for conjure-up

.gitignore, redirects.yaml, run, templates/index.html
QA
--
`./run clean`
`./run`
Check `http://127.0.0.1:8007/conjure-up/en/walkthrough?_ga=2.50604649.1181177546.1502958538-1953003874.1490003599` redirects through to new page.
=> Redirect old conjure-up URLs to new

Dockerfile, requirements.txt, webapp/settings.py
Provide the ID of the commit at which point the code was built, as a HTTP header in the response from the docker container.
For production - so we can easily see which version of the code is running on a unit.
QA
--
``` bash
$ docker build --tag docs .  # Check it complains without COMMIT_ID
The command '/bin/sh -c test -n "${COMMIT_ID}"' returned a non-zero code: 1
$ docker build --tag docs --build-arg COMMIT_ID=`git rev-parse HEAD` .  # Build with COMMIT_ID
$ docker run --rm --name docs-throwaway --daemonize --publish 80:80 docs
$ curl -I localhost | grep 'X-'
X-commit-ID: 018f47199c3709e9d0bceb33bef30546ee76e820
X-Hostname: 096dbd5ae462
$ docker kill docs-throwaway
```
=> Make commit_id an env var

build-docs.sh, package.json, redirects.yaml, webapp/tests/test_redirects.py
Phone docs are now built in their own system, direct from the phone-docs repo,
and https://docs.ubuntu.com/phone is now using that system.
This removes all mention of building phone docs from this repo.
QA
--
``` bash
./run clean
./run
```
Visit <127.0.0.1:8007/phone>, see that it 404s
=> Remove all references to phone docs

build-docs.sh
The docs have moved to the docs/ inside the core repo. Change the build
script to accommodate.
QA
--
Test the `master` branch with `./run build`. This should break, complaining that there's no `metadata.yaml` when it tried to build core docs.
Now checkout this branch and run `./run build`. This should hopefully succeed, with the core docs looking as they should.
=> Fix core build by using docs dir

redirects.yaml, webapp/tests/test_redirects.py
Sure up the redirects, and update Maas redirects to point to version 2.3
QA
--
``` bash
./run
```
Now go to <http://localhost:8007/maas>, <http://localhost:8007/maas/en/>, <http://localhost:8007/maas/2.3/> and check you end up on the homepage.
Go to <http://localhost:8007/maas/en/intro-concepts>, and check you end up at <https://docs.ubuntu.com/maas/2.3/en/intro-concepts>
=> Update redirects for maas 2.3

build-docs.sh, package.json, redirects.yaml, templates/index.html, webapp/tests/test_redirects.py
Please do review but do not merge just yet.
Remove docs build for `/conjure-up` and `maas`, and redirect to new domains.
- `./run`
- `curl -I http://0.0.0.0:8007/conjure-up/testing`  should redirect to docs.conjure-up.io and preserve the `/testing` path.
- `curl -I http://0.0.0.0:8007/maas/testing`  should redirect to docs.maas.io and preserve the `/testing` path.
- Visit http://0.0.0.0:8007/ and make sure it is error free. http://0.0.0.0:8007/documentation-builder/en/ should show the documentation builder docs.
Feel free to try some other paths for the redirect testing steps.
=> conjure-up and maas removal / redirections

templates/index.html
Conjure-up and maas docs sites can handle redirects to the defaults without hardcoding a version in the HTML here.
remove specific version for MAAS docs link
remove specific version for conjure-up docs link
see that the new links resolve to the correct default versions
=> Stop hardcoding  docs versions in the html

templates/includes/layout.html
Added the meta description to the head of the layout template.
- Go to any page and view-source
- Check there is a meta description
- Check the description matches the [copy doc](https://docs.google.com/document/d/1mcfPYByoIT_iFOot6fxqq_bXX9p9vENWkLt4-ZI22Qg/edit)
https://github.com/canonical-websites/docs.ubuntu.com/issues/164
=> Add meta description to the head of the layout

build-docs.sh, redirects.yaml, templates/index.html
- Rename docs from snap-enterprise-proxy to snap-store-proxy
- Add redirect from former to latter
- Verify redirects from /snap-enterprise-proxy/* to /snap-store-proxy/*
=> Rename docs from snap-enterprise-proxy to snap-store-proxy

templates/index.html
- fixed spelling of prov*i*des
- added a full stop
- ./run
- <http://0.0.0.0:8007>
- compare to the [copy doc](https://docs.google.com/document/d/1mcfPYByoIT_iFOot6fxqq_bXX9p9vENWkLt4-ZI22Qg/edit#heading=h.7gsn9t3mksj3)
=> fixed typos on docs.u.c homepage

Dockerfile, entrypoint, package.json, requirements.txt
Fixes https://github.com/ubuntudesign/base-squad/issues/98
QA
--
``` bash
./run
```
See that it mentions "Booting worker" 3 times. Go to http://localhost:8007 - browse around, check the site works. Then:
``` bash
docker build --tag docs --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run -ti -p 8099:80 docs
```
Go to http://localhost:8099 - similarly, see that it mentions "Booting worker" 3 times and check the site works.
Also, check the `X-VCS-Revision` shows correctly:
``` bash
$ curl -Is localhost:8099 | grep VCS
X-VCS-Revision: {commit_hash}
```
=> Add entrypoint for talisker gevent workers

requirements.txt
* Bump documentation-builder to 1.6.0
* See that site-wide-footer links are respected in /snap-store-proxy/en
Fixes #170
=> Bump documentation-builder to 1.6.0

Dockerfile, requirements.txt
This is so we can use `netstat` in a `livenessProbe` to check a process is running on port 80.
=> Add net-tools

templates/index.html
* Uploaded a bigger 'native' SVG to asset server
* Referenced it from index.html
* Is the snapcraft logo the same size as the other ones?
* Fixes #175
=> Use a larger snapcraft logo

redirects.yaml
* Change all redirects to accept empty pages, thereby coping with trailing slash
* Add /en to the snap-enterprise-proxy redirect, to avoid two redirects.
* Visit /snap-enterprise-proxy/ ; /maas/ ; /conjure-up/ and verify you're redirected.
Fixes #178
N/A
=> Fix redirects to also handle trailing slashes

redirects.yaml, requirements.txt, webapp/urls.py
Made search redirect to https://www.ubuntu.com/search
- Run `./run`
- Access `http://0.0.0.0:8007/search?q=https&domain=docs.ubuntu.com`
- Verify you were redirected to `https://www.ubuntu.com/search?q=https&domain=docs.ubuntu.com`
Fixes #183
=> Redirect searches to https://www.ubuntu.com/search

templates/index.html
This links to the new main Landscape docs site at docs.ubuntu.com/landscape/en/
The only reason to reject is if I made a silly mistake or if we want to change where it lives first aka #110 
[List of work items including drive-bys]
Confirm that docs.ubuntu.com's landscape links point to docs.ubuntu.com/landscape/en/
=> Landscape - We're ready to make the new site public / more visible

build-docs.sh, redirects.yaml, templates/index.html
Because documentation-builder is deprecated and no longer the recommended way to create documentation websites,
we shouldn't elevate its documentation by creating a website for it.
Instead, we'll now simply redirect the user to read the docs directly in the (deprecated) project repository.
QA
--
`./run`
Try going to:
- http://0.0.0.0:8007/ - check the homepage still works
- http://0.0.0.0:8007/documentation-builder
- http://0.0.0.0:8007/documentation-builder/en/
- http://0.0.0.0:8007/documentation-builder/en/structure
- http://0.0.0.0:8007/documentation-builder/en/homepage-examples/juju-example
Check, in each case, that you end up on a readable documentation page.
=> Remove and redirect /documentation-builder

redirects.yaml
The document has been renamed, so we need to redirect the old URL.
Fixes https://github.com/canonical-docs/landscape-docs/issues/82
Go to https://docs-ubuntu-com-canonical-websites-pr-207.run.demo.haus/landscape/en/landscape-api, see that you're redirected to https://docs-ubuntu-com-canonical-websites-pr-207.run.demo.haus/landscape/en/api.
Or to test it locally:
`./run`, then go to http://0.0.0.0:8007/landscape/en/landscape-api and check you are redirected to http://0.0.0.0:8007/landscape/en/api
=> Redirect landscape-api to api

package.json, templates/footer.html, templates/index.html, yarn.lock
- An updated version of the site to v2.0.1
- Updated components, classes, and utilities based on release notes [here](https://github.com/canonical-web-and-design/vanilla-framework/releases/tag/2.0.1)
1. Check out this feature branch
2. Run the site using the command `./run`
3. View the site locally in your web browser at: [http://0.0.0.0:8007/](http://0.0.0.0:8007/)
4. View the demo link at https://docs-ubuntu-com-canonical-web-and-design-pr-216.run.demo.haus/
=> Vanilla upgrade 2.0.1

Dockerfile, requirements.txt
It seems that gitdb breaks since v3.0.2 with this error:
```
Traceback (most recent call last):
File "/home/toto/.pyenv/versions/docs.ubuntu.com/bin/documentation-builder", line 8, in <module>
from ubuntudesign.documentation_builder import cli
File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/cli.py", line 7, in <module>
from .builder import Builder
File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/builder.py", line 19, in <module>
from .operations import (
File "/home/toto/.pyenv/versions/3.6.5/envs/docs.ubuntu.com/lib/python3.6/site-packages/ubuntudesign/documentation_builder/operations.py", line 13, in <module>
from git import Repo
File …
```
=> Change version gitdb since v3.0.2 breaks

templates/index.html
- Use help.ubuntu.com/stable/ubuntu-help for the desktop guide instead of help.ubuntu.com/lts/ubuntu-help
See that the desktop docs now goes to the /stable/ version
Fixes #154
=> Update desktop docs link

templates/index.html
- Update spelling of OpenStack
- Remove conjure-ip docs
- Updated the [copy doc](https://docs.google.com/document/d/1mcfPYByoIT_iFOot6fxqq_bXX9p9vENWkLt4-ZI22Qg/edit)
1. Dowload this branch and ./run
2. Look at http://0.0.0.0:8007/
3. See that OpenStack has the right titles and that conjure-up docs are removed
Fixes #248
=> Update spelling of OpenStack, remove conjure-ip docs

konf/site.yaml, redirects.yaml
Redirections for core, phone and security-certs
Build the docker image:
`DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag test .`
Run the website locally:
`docker run -ti -p "8007:80" --env SECRET_KEY=secret_key test`
Go to any of the following addresses and check that the redirection is working
https://docs.ubuntu.com/core/en/guides/build-device/board-enablement
https://docs.ubuntu.com/phone/en/platform/sdk/
https://docs.ubuntu.com/security-certs/en/fips-cloud-containers
Try with any address under /core, /phone or /security-certs you should get redirected to their new subdomains.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2970
=> Redirections for core, phone and security-certs

templates/index.html
- Add links to the MicroK8s, Charmed Kubernetes and Netplan documentation to index.html
- Check out this feature branch
- Run `./run` and visit http://0.0.0.0:8007/ to view locally in your browser
- Ensure that the aforementioned links are present, with appropriate descriptions and icons
- Ensure that the new code is consistent in style to the rest of the code
- If you know of any more documentation for Canonical products that have not been linked, let me know and I'll add it
Fixes #242
=> Add missing products to index.html

build-docs.sh, templates/includes/layout.html
- to make moving to the new cookie policy, I am moving as many sites out of the ubuntu.com container as possible
- download and `.run` (not dotrun) the site
- view the source and see the docs are now using the `GTM-KNX3CJC` container
Fixes #264
=> Move to a new GTM container

templates/index.html
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>
Update LXD docs URL to current location (https://linuxcontainers.org/lxd/docs/master/)
=> Update LXD docs URL to current location

build-docs.sh, redirects.yaml, templates/index.html
- Fixed styleguide homepage link
- Removed 'not very useful' search
See issues section for further info
- Check that https://docs-ubuntu-com-310.demos.haus/styleguide redirects to https://docs-ubuntu-com-310.demos.haus/styleguide/en. This fixes the homepage link on /styleguide
- Check on this very page that the search is removed.
Fixes https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/213
Fixes https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/158
=> Fix homepage URL and remove search

Dockerfile, requirements.txt
Pin `MarkupSafe` to avoid the `build-docs.sh` script breaking.
- Checkout branch and try to build the docs, make sure it succeeds.
=> Pin MarkupSafe to avoid the script breaking

Dockerfile
Current image is in an incomplete state because the templates being generated by documentation-builder were not being copied properly. You can check https://docs.staging.ubuntu.com/snap-store-proxy/en/ 404's.
- Checkout this branch
- `DOCKER_BUILDKIT=1 docker build -t docs .`
- `docker run -ti -p 8007:80 docs`
-  Go to localhost:8007/snap-store-proxy/en/ and make sure you see the page
=> Docker: Copy templates and media from the build-documentation stage

redirects.yaml, requirements.txt, templates/index.html
- Setup landscape docs redirect and update navigation link to the new ubuntu.com hosted docs
- Go to https://docs-ubuntu-com-350.demos.haus/landscape/en/ and see that you are redirected to https://ubuntu.com/landscape/docs
- Go to the home pages of https://docs-ubuntu-com-350.demos.haus/ and click the link for `Landscape`, see that it take you to https://ubuntu.com/landscape/docs
=> Setup landscape docs redirect and update navigation link

redirects.yaml
Add more redirects to move landscape documentation according to https://warthogs.atlassian.net/browse/WD-2513
Check:
- https://docs-ubuntu-com-357.demos.haus/landscape/en/  redirects to https://ubuntu.com/landscape/docs
- https://docs-ubuntu-com-357.demos.haus/landscape/en/landscape-install-quickstart  redirects to https://ubuntu.com/landscape/docs/quickstart-deployment
Closes https://warthogs.atlassian.net/browse/WD-2513
Closes https://warthogs.atlassian.net/browse/WD-3003
=> WD-2513 redirect landscape old docs to new docs

build-docs.sh
remove landscape from the build script - that repo has been archived due to docs being built from discourse now
Fixes #360 (I expect!)
=> remove landscape from build-docs.sh

templates/index.html
- Update link for Snap Store Proxy
- Copy update request: https://docs.google.com/document/d/1mcfPYByoIT_iFOot6fxqq_bXX9p9vENWkLt4-ZI22Qg/edit#heading=h.kirb2ro8pwcn
- Go to landing
- See that "Snap Store Proxy" redirects to https://canonical-snap-store-proxy.readthedocs-hosted.com/en/latest/
Fixes [WD-13621](https://warthogs.atlassian.net/browse/WD-13621)
[WD-13621]: https://warthogs.atlassian.net/browse/WD-13621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Snap Store Proxy link

build-docs.sh, redirects.yaml
- Removed snap-store-proxy from build-docs.sh
- Changed existing snap-enterprise-proxy redirect to RTD site
- Added redirects from old URL to RTD site
=> Remove snap store proxy generation and adds redirects

templates/index.html
Changed link from https://canonical-snap-store-proxy.readthedocs-hosted.com/en/latest/ to https://documentation.ubuntu.com/snap-store-proxy for Snap Store Proxy on docs.ubuntu.com
Go to docs.ubuntu.com
Click on the link at Snap Store Proxy
Should be redirected to [https://documentation.ubuntu.com/snap-store-proxy](https://documentation.ubuntu.com/snap-store-proxy)
Fixes [#WD-14658](https://warthogs.atlassian.net/browse/WD-14658)
=> change url for snap store proxy

redirects.yaml
Changes Snap Store Proxy redirects to https://documentation.ubuntu.com/snap-store-proxy
=> Update Snap Store Proxy redirect URLs

package.json, templates/includes/layout.html, yarn.lock
- Invoke cookie policy before google tag manager
Fixes https://warthogs.atlassian.net/browse/WD-15825
=> Run cookie policy before GTM

.github/workflows/pr.yaml, templates/index.html
Added an entry for Real-time Ubuntu documentation in the landing page.
Verified that `./run` builds with no errors locally and rendered HTML is as expected.
N/A
=> index: add real-time ubuntu docs entry

templates/index.html
[Chisel](https://documentation.ubuntu.com/chisel/en/latest/) and [Rockcraft](https://documentation.ubuntu.com/rockcraft/en/stable/#) added to the index page.
Verified the build locally.
Fixes https://warthogs.atlassian.net/browse/WD-19634
=> index: Add Chisel and Rockcraft to the index page

templates/index.html
Added Product Table requested from the TA [Epic](https://warthogs.atlassian.net/browse/DOCPR-960?atlOrigin=eyJpIjoiZDUzMWUzZjllZDM2NGFmYzllMTcxOTgwMzk3YzVlYWIiLCJwIjoiaiJ9) based on the following [file](https://docs.google.com/spreadsheets/d/1HxWy9mNdsuAeo6C6I1h-w5McmKrgL8GP9p5ybDFP7mE/edit?gid=389860526#gid=389860526)
Check all the spreadsheet link work in the same way as the Table in docs.u.com
=> feat: add the documentation table of products to page
